### ISSUE TITLE
Extract the bitmask libraries that we have in a separate python library

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#30]
we had this on example.wz as well as on dev.wz. 
on example.wz, it happened also on logging in with the useragent. i can't reproduce on dev.wz because i can't remember a valid user/pw combination, but on registering we get the same error:

```
(.virtualenv)--- git/pixelated-user-agent ‹master› » pixelated-user-agent --register dev.wazokazi.is varac56 --debug
2014-11-26 09:55:58+0100 [-] Log opened.
2014-11-26 09:55:58+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): dev.wazokazi.is
2014-11-26 09:55:58+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "GET /provider.json HTTP/1.1" 200 872
Please enter password for varac56: 
2014-11-26 09:56:01+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): api.dev.wazokazi.is
2014-11-26 09:56:04+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "POST /1/users HTTP/1.1" 201 29
2014-11-26 09:56:04+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): dev.wazokazi.is
2014-11-26 09:56:04+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "GET /provider.json HTTP/1.1" 200 872
2014-11-26 09:56:04+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): dev.wazokazi.is
2014-11-26 09:56:05+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "GET /ca.crt HTTP/1.1" 200 2009
2014-11-26 09:56:05+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): api.dev.wazokazi.is
2014-11-26 09:56:06+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "POST /1/sessions HTTP/1.1" 200 282
2014-11-26 09:56:09+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "PUT /1/sessions/varac56 HTTP/1.1" 200 167
2014-11-26 09:56:09+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): api.dev.wazokazi.is
2014-11-26 09:56:10+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "GET /1/config/soledad-service.json HTTP/1.1" 200 200
2014-11-26 09:56:11+0100 [-] leap.soledad.client.secrets: WARNING  IOError while loading secrets from disk: File does not exist: /home/varac/.leap/soledad/d7a4b4b40a6db10ed5b21358ee2b46e8.secret
2014-11-26 09:56:11+0100 [-] leap.soledad.client.secrets: INFO     Trying to fetch cryptographic secrets from shared recovery database...
2014-11-26 09:56:14+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_DOWNLOADING_KEYS
2014-11-26 09:56:14+0100 [-] content:
2014-11-26 09:56:15+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_DONE_DOWNLOADING_KEYS
2014-11-26 09:56:15+0100 [-] con
2014-11-26 09:56:15+0100 [-] leap.soledad.client.secrets: INFO     No cryptographic secrets found, creating new  secrets...
2014-11-26 09:56:15+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_CREATING_KEYS
2014-11-26 09:56:15+0100 [-] content: "d
2014-11-26 09:56:15+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_DONE_CREATING_KEYS
2014-11-26 09:56:15+0100 [-] conten
2014-11-26 09:56:15+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_DOWNLOADING_KEYS
2014-11-26 09:56:15+0100 [-] content:
2014-11-26 09:56:15+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_DONE_DOWNLOADING_KEYS
2014-11-26 09:56:15+0100 [-] con
2014-11-26 09:56:15+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_UPLOADING_KEYS
2014-11-26 09:56:15+0100 [-] content: "
2014-11-26 09:56:16+0100 [-] leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_DONE_UPLOADING_KEYS
2014-11-26 09:56:16+0100 [-] conte
2014-11-26 09:56:18+0100 [-] leap.soledad.client.sqlcipher: DEBUG    SQLCIPHER: SETTING SYNCHRONOUS NORMAL
2014-11-26 09:56:19+0100 [-] leap.mail.imap.mailbox: INFO     Priming Soledad last_uid to 0
2014-11-26 09:56:19+0100 [-] leap.mail.imap.memorystore: INFO     setting last soledad uid for INBOX to 0
2014-11-26 09:56:19+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): api.dev.wazokazi.is
2014-11-26 09:56:19+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "GET /1/config/smtp-service.json HTTP/1.1" 200 200
2014-11-26 09:56:19+0100 [-] SMTP server running on port 4650
2014-11-26 09:56:19+0100 [-] requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): api.dev.wazokazi.is
2014-11-26 09:56:20+0100 [-] requests.packages.urllib3.connectionpool: DEBUG    "GET /1/cert HTTP/1.1" 401 82
2014-11-26 09:56:20+0100 [-] Traceback (most recent call last):
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/bin/pixelated-user-agent", line 9, in <module>
2014-11-26 09:56:20+0100 [-]     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/runserver.py", line 48, in setup
2014-11-26 09:56:20+0100 [-]     register(*args.register[::-1])
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/runserver.py", line 67, in register
2014-11-26 09:56:20+0100 [-]     leap_register.register_new_user(username, server_name)
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/bitmask_libraries/register.py", line 33, in register_new_user
2014-11-26 09:56:20+0100 [-]     session = LeapSession.open(username, password, server_name)
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/bitmask_libraries/session.py", line 43, in open
2014-11-26 09:56:20+0100 [-]     session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/bitmask_libraries/session.py", line 120, in create
2014-11-26 09:56:20+0100 [-]     session = self._create_new_session(credentials)
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/bitmask_libraries/session.py", line 138, in _create_new_session
2014-11-26 09:56:20+0100 [-]     smtp.start()
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/bitmask_libraries/smtp.py", line 75, in start
2014-11-26 09:56:20+0100 [-]     self._download_client_certificates()
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/bitmask_libraries/smtp.py", line 60, in _download_client_certificates
2014-11-26 09:56:20+0100 [-]     response.raise_for_status()
2014-11-26 09:56:20+0100 [-]   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/requests-2.4.3-py2.7.egg/requests/models.py", line 825, in raise_for_status
2014-11-26 09:56:20+0100 [-]     raise HTTPError(http_error_msg, response=self)
2014-11-26 09:56:20+0100 [-] requests.exceptions.HTTPError: 401 Client Error: Authorization Required

```

Before, 0.6rc1 was deployed to both environments. Yesterday, i delpoyed latest leap_platform:develop with latest leap_cli:develop, and it broke afterwards.
The workaround is this to allow anonymous cert downloads which are used for the vpn service (which we don't use), but it disables the authentication on /1/cert:

```
diff --git a/provider.json b/provider.json
index 5ee8a64..e67f635 100644
--- a/provider.json
+++ b/provider.json
@@ -14,5 +14,9 @@
   },
   "languages": ["en"],
   "default_language": "en",
-  "enrollment_policy": "open"
+  "enrollment_policy": "open",
+  "service": {
+    "allow_anonymous": true,
+    "levels": {}
+  }
 }

```

i deployed with this change to example.wz and the useragent is working again.

I suspect this change in leap_cli: https://leap.se/code/issues/6412#note-3 to introduce this regression, because it rewrote the "eip_service:" in the hiera file, but i'm not sure and elijah needs to look after this.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
