### ISSUE TITLE
tests on staging fail

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#98]
I get this error when running the tests:
```
TypeError: wait_until_element_is_visible_by_locator() takes exactly 3 arguments (2 given)
```

**Comment by GavinSchalliol** [comment]
...so I think the above error was fixed by 340ea579e56033ec80159dba825ace913c111fc6 from @tiagoferraz 

...now waiting for the next run of functional tests...

**Comment by GavinSchalliol** [comment]
Now we see:

```
  @login
  Scenario: user goes to dispatcher and enters credentials  # account.feature:36
    When I visit the dispatcher                             # steps/account.py:34
    And I login                                             # steps/account.py:44
    Then I see the inbox                                    # steps/account.py:51
      Traceback (most recent call last):
        File "/var/go/.virtualenvs/pixelated-platform-behave/local/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/var/go/.virtualenvs/pixelated-platform-behave/local/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/var/lib/go-agent/pipelines/staging.pixela/pixelated-platform/test/features/steps/account.py", line 57, in step_impl
          taglist.is_pixelated_loaded()
        File "/var/lib/go-agent/pipelines/staging.pixela/pixelated-platform/test/features/page_objects/tag_list.py", line 61, in is_pixelated_loaded
          self.wait_until_element_is_visible_by_locator(self._locators['inbox'])
        File "/var/lib/go-agent/pipelines/staging.pixela/pixelated-platform/test/features/page_objects/base_page_object.py", line 77, in wait_until_element_is_visible_by_locator
          by, locator = locator
      ValueError: too many values to unpack
```

**Comment by GavinSchalliol** [comment]
@tiagoferraz the behave tests are still failing -- are you sure this should be closed?

**Comment by tiagoferraz** [comment]
Yes. This specific error was fixed and the code for the tests are correct. Yet they fail because of problems in our environment.
